version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: mitrama_rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mitrama_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SenhaForte!123 
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  backend:
    image: mitrama-api
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: mitrama_backend
    ports:
      - "5253:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Conexão com a DB (serviço "db")
      - ConnectionStrings__DefaultConnection=Server=db;Database=TramaDb;User Id=sa;Password=SenhaForte!123;TrustServerCertificate=True;
      # Conexão com RabbitMQ (serviço "rabbitmq")
      - ConnectionStrings__RabbitMQ=rabbitmq
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  frontend:
    image: mitrama-web
    build:
      context: ./FrontEnd/frontend-marketplace 
      dockerfile: Dockerfile
    container_name: mitrama_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  sqlvolume: