name: Deploy Frontend (Angular) to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: FrontEnd/frontend-marktplace/package-lock.json 
          
      - name: Install Dependencies
        run: npm ci 
        working-directory: ./FrontEnd/frontend-marktplace/

      - name: Build Angular Application
        run: npm run build -- --output-path=docs --base-href=/MarketingPlace/
        working-directory: ./FrontEnd/frontend-marktplace/

      - name: Create .nojekyll file
        run: touch FrontEnd/frontend-marktplace/docs/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'FrontEnd/frontend-marktplace/docs' 
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4