name: Build & Test - .NET API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./MarketingPlace/BackEnd/MarketplaceArtesanato.sln

      - name: Build
        run: dotnet build ./MarketingPlace/BackEnd/MarketplaceArtesanato.sln --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test ./MarketingPlace/BackEnd/MarketplaceArtesanato.Tests/MarketplaceArtesanato.Tests.csproj --no-build --verbosity normal

      - name: Publish API
        run: dotnet publish ./MarketingPlace/BackEnd/MarketplaceArtesanato.API/MarketplaceArtesanato.API.csproj -c Release -o ./publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: MarketplaceArtesanato-API
          path: ./publish
